# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_firmware_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_firmware_update(object):
    def setupUi(self, tool_firmware_update):
        tool_firmware_update.setObjectName("tool_firmware_update")
        tool_firmware_update.resize(600, 260)
        tool_firmware_update.setMinimumSize(QtCore.QSize(600, 260))
        tool_firmware_update.setMaximumSize(QtCore.QSize(600, 260))
        tool_firmware_update.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color : rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(tool_firmware_update)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 600, 161))
        self.groupBox.setMinimumSize(QtCore.QSize(600, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 30, 284, 95))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 95))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    \n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/固件升级.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit.setStyleSheet("border : none;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(120, 30, 84, 95))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 95))
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 200, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 91, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 157, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 200, 76, 32))
        self.pushButton_3.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_3.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        tool_firmware_update.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_firmware_update)
        self.statusbar.setObjectName("statusbar")
        tool_firmware_update.setStatusBar(self.statusbar)

        self.retranslateUi(tool_firmware_update)
        QtCore.QMetaObject.connectSlotsByName(tool_firmware_update)

    def retranslateUi(self, tool_firmware_update):
        _translate = QtCore.QCoreApplication.translate
        tool_firmware_update.setWindowTitle(_translate("tool_firmware_update", "固件升级"))
        self.pushButton.setText(_translate("tool_firmware_update", "添加文件"))
        self.lineEdit.setPlaceholderText(_translate("tool_firmware_update", "3.54.46.bin"))
        self.label.setText(_translate("tool_firmware_update", "选择文件"))
        self.label_2.setText(_translate("tool_firmware_update", "文件名称"))
        self.pushButton_2.setText(_translate("tool_firmware_update", "确定"))
        self.label_3.setText(_translate("tool_firmware_update", "已选择设备数:"))
        self.pushButton_3.setText(_translate("tool_firmware_update", "取消"))
import shuncom_qrc_rc
