# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_change_server_point.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_change_server_point(object):
    def setupUi(self, tool_change_server_point):
        tool_change_server_point.setObjectName("tool_change_server_point")
        tool_change_server_point.resize(770, 700)
        tool_change_server_point.setMinimumSize(QtCore.QSize(770, 700))
        tool_change_server_point.setMaximumSize(QtCore.QSize(770, 700))
        tool_change_server_point.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(tool_change_server_point)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 771, 621))
        self.groupBox.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 250, 542))
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 542))
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 542))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(70, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"   \n"
"    /*字体颜色*/ \n"
"    color: rgba(50, 50, 51, 180);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/新增.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(70, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(70, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgba(50, 50, 51, 180);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/删除1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(248, 510))
        self.tableWidget.setMaximumSize(QtCore.QSize(248, 510))
        self.tableWidget.setStyleSheet("QTableWidget\n"
"{\n"
"    border : none;\n"
"    background-color: rgb(247, 248, 250);\n"
"}")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(248)
        self.tableWidget.verticalHeader().setMinimumSectionSize(56)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(105, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 10, 470, 542))
        self.groupBox_3.setMinimumSize(QtCore.QSize(470, 542))
        self.groupBox_3.setMaximumSize(QtCore.QSize(470, 542))
        self.groupBox_3.setStyleSheet("background-color: rgb(247, 248, 250);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 470, 130))
        self.groupBox_4.setMinimumSize(QtCore.QSize(470, 130))
        self.groupBox_4.setMaximumSize(QtCore.QSize(470, 130))
        self.groupBox_4.setStyleSheet("border : none;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setMinimumSize(QtCore.QSize(115, 95))
        self.groupBox_7.setMaximumSize(QtCore.QSize(115, 95))
        self.groupBox_7.setStyleSheet("")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setMinimumSize(QtCore.QSize(285, 95))
        self.groupBox_6.setMaximumSize(QtCore.QSize(285, 95))
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.mode_1 = QtWidgets.QGroupBox(self.groupBox_3)
        self.mode_1.setGeometry(QtCore.QRect(0, 130, 470, 411))
        self.mode_1.setMinimumSize(QtCore.QSize(470, 0))
        self.mode_1.setMaximumSize(QtCore.QSize(470, 16777215))
        self.mode_1.setStyleSheet("border : none;")
        self.mode_1.setTitle("")
        self.mode_1.setObjectName("mode_1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.mode_1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_11 = QtWidgets.QGroupBox(self.mode_1)
        self.groupBox_11.setMinimumSize(QtCore.QSize(115, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(115, 16777215))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_36 = QtWidgets.QLabel(self.groupBox_11)
        self.label_36.setMinimumSize(QtCore.QSize(0, 32))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setMinimumSize(QtCore.QSize(0, 32))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setMinimumSize(QtCore.QSize(0, 32))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setMinimumSize(QtCore.QSize(0, 32))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_11)
        self.label_12.setMinimumSize(QtCore.QSize(0, 32))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setMinimumSize(QtCore.QSize(0, 32))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setMinimumSize(QtCore.QSize(0, 32))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_11)
        self.label_35.setMinimumSize(QtCore.QSize(0, 32))
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        self.label_37.setMinimumSize(QtCore.QSize(0, 32))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 5, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_11, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.mode_1)
        self.groupBox_12.setMinimumSize(QtCore.QSize(285, 0))
        self.groupBox_12.setMaximumSize(QtCore.QSize(285, 16777215))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_8.setMinimumSize(QtCore.QSize(150, 32))
        self.groupBox_8.setMaximumSize(QtCore.QSize(150, 32))
        self.groupBox_8.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_4.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_4.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_2.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox_2.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_2, 5, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_8.addWidget(self.lineEdit_14, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 7, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_8.addWidget(self.lineEdit_9, 1, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_8.addWidget(self.lineEdit_13, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 3, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_10.setMinimumSize(QtCore.QSize(150, 32))
        self.groupBox_10.setMaximumSize(QtCore.QSize(150, 32))
        self.groupBox_10.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_6.addWidget(self.radioButton_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_6.addWidget(self.radioButton_4, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 8, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_8.addWidget(self.lineEdit_15, 6, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.mode_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.mode_2.setGeometry(QtCore.QRect(0, 130, 470, 411))
        self.mode_2.setMinimumSize(QtCore.QSize(470, 0))
        self.mode_2.setMaximumSize(QtCore.QSize(470, 16777215))
        self.mode_2.setStyleSheet("border : none;")
        self.mode_2.setTitle("")
        self.mode_2.setObjectName("mode_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.mode_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_14 = QtWidgets.QGroupBox(self.mode_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(115, 0))
        self.groupBox_14.setMaximumSize(QtCore.QSize(115, 16777215))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_21 = QtWidgets.QLabel(self.groupBox_14)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_14)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_14)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_14)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_14)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_14)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_14)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_14)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_14)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_14, 0, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.mode_2)
        self.groupBox_15.setMinimumSize(QtCore.QSize(285, 371))
        self.groupBox_15.setMaximumSize(QtCore.QSize(285, 371))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_15.addWidget(self.lineEdit_4, 2, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 32))
        self.comboBox_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_5, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_15.addWidget(self.lineEdit_8, 8, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_15.addWidget(self.lineEdit_7, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_15.addWidget(self.lineEdit_5, 4, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_15.addWidget(self.lineEdit_6, 5, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_17.setMinimumSize(QtCore.QSize(260, 32))
        self.groupBox_17.setMaximumSize(QtCore.QSize(260, 32))
        self.groupBox_17.setStyleSheet("")
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_13.addWidget(self.radioButton_8, 0, 0, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_13.addWidget(self.radioButton_9, 0, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_13.addWidget(self.radioButton_10, 0, 2, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_17, 3, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_16.setMinimumSize(QtCore.QSize(260, 32))
        self.groupBox_16.setMaximumSize(QtCore.QSize(260, 32))
        self.groupBox_16.setStyleSheet("")
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_16)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_12.addWidget(self.radioButton_5, 0, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_12.addWidget(self.radioButton_7, 0, 2, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_16)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_12.addWidget(self.radioButton_6, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_16, 1, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_15.addWidget(self.lineEdit_16, 7, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_15, 0, 1, 1, 1)
        self.mode_3 = QtWidgets.QGroupBox(self.groupBox_3)
        self.mode_3.setGeometry(QtCore.QRect(0, 130, 470, 411))
        self.mode_3.setMinimumSize(QtCore.QSize(470, 0))
        self.mode_3.setMaximumSize(QtCore.QSize(470, 16777215))
        self.mode_3.setStyleSheet("border : none;")
        self.mode_3.setTitle("")
        self.mode_3.setObjectName("mode_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.mode_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_20 = QtWidgets.QGroupBox(self.mode_3)
        self.groupBox_20.setMinimumSize(QtCore.QSize(115, 95))
        self.groupBox_20.setMaximumSize(QtCore.QSize(115, 251))
        self.groupBox_20.setStyleSheet("")
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_29 = QtWidgets.QLabel(self.groupBox_20)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_17.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_20)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_17.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_20)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_20)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_17.addWidget(self.label_30, 5, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_20)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_17.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_20)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_17.addWidget(self.label_27, 2, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_20, 0, 0, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.mode_3)
        self.groupBox_21.setMinimumSize(QtCore.QSize(285, 0))
        self.groupBox_21.setMaximumSize(QtCore.QSize(285, 251))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_18.addWidget(self.lineEdit_10, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_21)
        self.comboBox_3.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox_3.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_3, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_18.addWidget(self.lineEdit_12, 5, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_18.addWidget(self.lineEdit_11, 4, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_21)
        self.comboBox_4.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox_4.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox_4.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_4, 6, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_18.addWidget(self.lineEdit_17, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_21, 0, 1, 1, 1)
        self.groupBox_4.raise_()
        self.mode_3.raise_()
        self.mode_2.raise_()
        self.mode_1.raise_()
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 640, 76, 32))
        self.pushButton_3.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_3.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 640, 76, 32))
        self.pushButton_4.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_4.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 91, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 650, 157, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        tool_change_server_point.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_change_server_point)
        self.statusbar.setObjectName("statusbar")
        tool_change_server_point.setStatusBar(self.statusbar)

        self.retranslateUi(tool_change_server_point)
        self.radioButton.clicked['bool'].connect(self.lineEdit_9.close)
        self.radioButton.clicked['bool'].connect(self.lineEdit_13.close)
        self.radioButton.clicked['bool'].connect(self.lineEdit_2.close)
        self.radioButton.clicked['bool'].connect(self.lineEdit_14.close)
        self.radioButton.clicked['bool'].connect(self.comboBox_2.close)
        self.radioButton.clicked['bool'].connect(self.label_9.close)
        self.radioButton.clicked['bool'].connect(self.label_35.close)
        self.radioButton.clicked['bool'].connect(self.label_10.close)
        self.radioButton.clicked['bool'].connect(self.label_36.close)
        self.radioButton.clicked['bool'].connect(self.label_37.close)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_9.show)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_13.show)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_2.show)
        self.radioButton_2.clicked['bool'].connect(self.lineEdit_14.show)
        self.radioButton_2.clicked['bool'].connect(self.comboBox_2.show)
        self.radioButton_2.clicked['bool'].connect(self.label_9.show)
        self.radioButton_2.clicked['bool'].connect(self.label_35.show)
        self.radioButton_2.clicked['bool'].connect(self.label_10.show)
        self.radioButton_2.clicked['bool'].connect(self.label_36.show)
        self.radioButton_2.clicked['bool'].connect(self.label_37.show)
        self.radioButton.clicked['bool'].connect(self.label_13.show)
        self.radioButton.clicked['bool'].connect(self.groupBox_10.show)
        self.radioButton_2.clicked['bool'].connect(self.label_13.close)
        self.radioButton_2.clicked['bool'].connect(self.groupBox_10.close)
        self.radioButton_6.clicked['bool'].connect(self.lineEdit_4.close)
        self.radioButton_9.clicked['bool'].connect(self.lineEdit_5.close)
        self.radioButton_7.clicked['bool'].connect(self.lineEdit_4.show)
        self.radioButton_5.clicked['bool'].connect(self.lineEdit_4.show)
        self.radioButton_10.clicked['bool'].connect(self.lineEdit_5.show)
        self.radioButton_8.clicked['bool'].connect(self.lineEdit_5.show)
        self.radioButton_6.clicked['bool'].connect(self.label_15.close)
        self.radioButton_9.clicked['bool'].connect(self.label_17.close)
        self.radioButton_5.clicked['bool'].connect(self.label_15.show)
        self.radioButton_8.clicked['bool'].connect(self.label_17.show)
        self.radioButton_7.clicked['bool'].connect(self.label_15.show)
        self.radioButton_10.clicked['bool'].connect(self.label_17.show)
        QtCore.QMetaObject.connectSlotsByName(tool_change_server_point)

    def retranslateUi(self, tool_change_server_point):
        _translate = QtCore.QCoreApplication.translate
        tool_change_server_point.setWindowTitle(_translate("tool_change_server_point", "修改服务器指向"))
        self.pushButton.setText(_translate("tool_change_server_point", "新增"))
        self.pushButton_2.setText(_translate("tool_change_server_point", "删除"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("tool_change_server_point", "sziot(sziot)"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("tool_change_server_point", "sztt_cloud(Touchuan)"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("tool_change_server_point", "mqtt_server(MQTT)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("tool_change_server_point", "连接名称"))
        self.label_2.setText(_translate("tool_change_server_point", "服务类型"))
        self.comboBox.setItemText(0, _translate("tool_change_server_point", "sziot"))
        self.comboBox.setItemText(1, _translate("tool_change_server_point", "Touchuan"))
        self.comboBox.setItemText(2, _translate("tool_change_server_point", "MQTT"))
        self.label_36.setText(_translate("tool_change_server_point", "发布主题"))
        self.label_13.setText(_translate("tool_change_server_point", "数据加密"))
        self.label_10.setText(_translate("tool_change_server_point", "订阅主题"))
        self.label_11.setText(_translate("tool_change_server_point", "服务器IP"))
        self.label_12.setText(_translate("tool_change_server_point", "服务器端口"))
        self.label_8.setText(_translate("tool_change_server_point", "协议类型"))
        self.label_9.setText(_translate("tool_change_server_point", "用户名"))
        self.label_35.setText(_translate("tool_change_server_point", "密码"))
        self.label_37.setText(_translate("tool_change_server_point", "发布QoS"))
        self.radioButton.setText(_translate("tool_change_server_point", "TCP"))
        self.radioButton_2.setText(_translate("tool_change_server_point", "MQTT"))
        self.comboBox_2.setItemText(0, _translate("tool_change_server_point", "2"))
        self.comboBox_2.setItemText(1, _translate("tool_change_server_point", "1"))
        self.comboBox_2.setItemText(2, _translate("tool_change_server_point", "0"))
        self.lineEdit_14.setText(_translate("tool_change_server_point", "topic"))
        self.lineEdit_3.setText(_translate("tool_change_server_point", "43219"))
        self.lineEdit_2.setText(_translate("tool_change_server_point", "topic"))
        self.radioButton_3.setText(_translate("tool_change_server_point", "是"))
        self.radioButton_4.setText(_translate("tool_change_server_point", "否"))
        self.label_21.setText(_translate("tool_change_server_point", "服务器端口"))
        self.label_17.setText(_translate("tool_change_server_point", "心跳包数据"))
        self.label_18.setText(_translate("tool_change_server_point", "心跳间隔(s)"))
        self.label_15.setText(_translate("tool_change_server_point", "注册数据"))
        self.label_16.setText(_translate("tool_change_server_point", "心跳包类型"))
        self.label_14.setText(_translate("tool_change_server_point", "注册数据类型"))
        self.label_20.setText(_translate("tool_change_server_point", "服务器IP"))
        self.label_19.setText(_translate("tool_change_server_point", "本地主题"))
        self.label_34.setText(_translate("tool_change_server_point", "数据来源"))
        self.lineEdit_4.setText(_translate("tool_change_server_point", "DC6F009815"))
        self.comboBox_5.setItemText(0, _translate("tool_change_server_point", "module1"))
        self.comboBox_5.setItemText(1, _translate("tool_change_server_point", "v2ctrl"))
        self.comboBox_5.setItemText(2, _translate("tool_change_server_point", "kl17_collect"))
        self.comboBox_5.setItemText(3, _translate("tool_change_server_point", "RS485-1"))
        self.comboBox_5.setItemText(4, _translate("tool_change_server_point", "32mcu"))
        self.lineEdit_8.setText(_translate("tool_change_server_point", "43219"))
        self.lineEdit_7.setText(_translate("tool_change_server_point", "topic"))
        self.lineEdit_5.setText(_translate("tool_change_server_point", "DC6F009815"))
        self.lineEdit_6.setText(_translate("tool_change_server_point", "30"))
        self.radioButton_8.setText(_translate("tool_change_server_point", "HEX"))
        self.radioButton_9.setText(_translate("tool_change_server_point", "OFF"))
        self.radioButton_10.setText(_translate("tool_change_server_point", "ASCII"))
        self.radioButton_5.setText(_translate("tool_change_server_point", "HEX"))
        self.radioButton_7.setText(_translate("tool_change_server_point", "ASCII"))
        self.radioButton_6.setText(_translate("tool_change_server_point", "OFF"))
        self.label_29.setText(_translate("tool_change_server_point", "密码"))
        self.label_28.setText(_translate("tool_change_server_point", "用户名"))
        self.label_25.setText(_translate("tool_change_server_point", "mqtt broker"))
        self.label_30.setText(_translate("tool_change_server_point", "发布QoS"))
        self.label_26.setText(_translate("tool_change_server_point", "ip"))
        self.label_27.setText(_translate("tool_change_server_point", "端口"))
        self.comboBox_3.setItemText(0, _translate("tool_change_server_point", "common"))
        self.comboBox_4.setItemText(0, _translate("tool_change_server_point", "0"))
        self.comboBox_4.setItemText(1, _translate("tool_change_server_point", "1"))
        self.comboBox_4.setItemText(2, _translate("tool_change_server_point", "2"))
        self.pushButton_3.setText(_translate("tool_change_server_point", "取消"))
        self.pushButton_4.setText(_translate("tool_change_server_point", "确定"))
        self.label_3.setText(_translate("tool_change_server_point", "已选择设备数:"))
import shuncom_qrc_rc
