# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_change.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_change(object):
    def setupUi(self, tool_change):
        tool_change.setObjectName("tool_change")
        tool_change.resize(600, 260)
        tool_change.setMinimumSize(QtCore.QSize(600, 260))
        tool_change.setMaximumSize(QtCore.QSize(600, 260))
        tool_change.setStyleSheet("\n"
"QMainWindow\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        tool_change.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(tool_change)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 601, 161))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 30, 285, 110))
        self.groupBox_2.setMinimumSize(QtCore.QSize(285, 110))
        self.groupBox_2.setMaximumSize(QtCore.QSize(285, 110))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit.setStyleSheet("border : none;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(89, 30, 91, 110))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 110))
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 157, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 200, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 200, 76, 32))
        self.pushButton.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 133, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        tool_change.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_change)
        self.statusbar.setObjectName("statusbar")
        tool_change.setStatusBar(self.statusbar)

        self.retranslateUi(tool_change)
        QtCore.QMetaObject.connectSlotsByName(tool_change)

    def retranslateUi(self, tool_change):
        _translate = QtCore.QCoreApplication.translate
        tool_change.setWindowTitle(_translate("tool_change", "修改Zigbee主站"))
        self.comboBox.setItemText(0, _translate("tool_change", "00(2.405GHz)"))
        self.comboBox.setItemText(1, _translate("tool_change", "01(2.410GHz)"))
        self.comboBox.setItemText(2, _translate("tool_change", "02(2.415GHz)"))
        self.comboBox.setItemText(3, _translate("tool_change", "03(2.420GHz)"))
        self.comboBox.setItemText(4, _translate("tool_change", "04(2.425GHz)"))
        self.comboBox.setItemText(5, _translate("tool_change", "05(2.430GHz)"))
        self.comboBox.setItemText(6, _translate("tool_change", "06(2.435GHz)"))
        self.comboBox.setItemText(7, _translate("tool_change", "07(2.440GHz)"))
        self.comboBox.setItemText(8, _translate("tool_change", "08(2.445GHz)"))
        self.comboBox.setItemText(9, _translate("tool_change", "09(2.450GHz)"))
        self.comboBox.setItemText(10, _translate("tool_change", "0A(2.455GHz)"))
        self.comboBox.setItemText(11, _translate("tool_change", "0B(2.460GHz)"))
        self.comboBox.setItemText(12, _translate("tool_change", "0C(2.465GHz)"))
        self.comboBox.setItemText(13, _translate("tool_change", "0D(2.470GHz)"))
        self.comboBox.setItemText(14, _translate("tool_change", "0E(2.475GHz)"))
        self.comboBox.setItemText(15, _translate("tool_change", "0F(2.480GHz)"))
        self.lineEdit.setPlaceholderText(_translate("tool_change", "请输入四位数16进制"))
        self.label.setText(_translate("tool_change", "频点:"))
        self.label_2.setText(_translate("tool_change", "频点ID:"))
        self.label_3.setText(_translate("tool_change", "已选择设备数:"))
        self.pushButton_2.setText(_translate("tool_change", "取消"))
        self.pushButton.setText(_translate("tool_change", "确定"))
import shuncom_qrc_rc
