# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_check_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_check_time(object):
    def setupUi(self, tool_check_time):
        tool_check_time.setObjectName("tool_check_time")
        tool_check_time.resize(600, 395)
        tool_check_time.setMinimumSize(QtCore.QSize(600, 395))
        tool_check_time.setMaximumSize(QtCore.QSize(600, 395))
        tool_check_time.setStyleSheet("QMainWindow\n"
"{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(tool_check_time)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 601, 291))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 20, 93, 201))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 20, 363, 251))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("border: none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 32))
        self.groupBox_4.setMaximumSize(QtCore.QSize(130, 32))
        self.groupBox_4.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 0, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 2, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(0, 32))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_6.setStyleSheet("color: rgb(200, 201, 204);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setMinimumSize(QtCore.QSize(260, 32))
        self.groupBox_5.setMaximumSize(QtCore.QSize(260, 32))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(205, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(205, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setMinimumSize(QtCore.QSize(52, 30))
        self.label_5.setMaximumSize(QtCore.QSize(52, 30))
        self.label_5.setStyleSheet("background-color: rgb(247, 248, 250);\n"
"color: rgb(100, 101, 102);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 3, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(0, 32))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label_7.setStyleSheet("color: rgb(200, 201, 204);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 3, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(76, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 91, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 4, 2, 1, 2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 340, 157, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        tool_check_time.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_check_time)
        self.statusbar.setObjectName("statusbar")
        tool_check_time.setStatusBar(self.statusbar)

        self.retranslateUi(tool_check_time)
        QtCore.QMetaObject.connectSlotsByName(tool_check_time)

    def retranslateUi(self, tool_check_time):
        _translate = QtCore.QCoreApplication.translate
        tool_check_time.setWindowTitle(_translate("tool_check_time", "校时"))
        self.label.setText(_translate("tool_check_time", "NTP设置"))
        self.label_2.setText(_translate("tool_check_time", "NTP服务器"))
        self.label_3.setText(_translate("tool_check_time", "NTP端口"))
        self.label_4.setText(_translate("tool_check_time", "更新周期"))
        self.radioButton.setText(_translate("tool_check_time", "是"))
        self.radioButton_2.setText(_translate("tool_check_time", "否"))
        self.lineEdit_2.setText(_translate("tool_check_time", "123"))
        self.label_6.setText(_translate("tool_check_time", "(0~65535)"))
        self.label_5.setText(_translate("tool_check_time", "分钟"))
        self.label_7.setText(_translate("tool_check_time", "(0~65535)"))
        self.pushButton_2.setText(_translate("tool_check_time", "取消"))
        self.pushButton.setText(_translate("tool_check_time", "确定"))
        self.label_8.setText(_translate("tool_check_time", "已选择设备数:"))
import shuncom_qrc_rc
