# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_server_pointing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_server_pointing(object):
    def setupUi(self, New_server_pointing):
        New_server_pointing.setObjectName("New_server_pointing")
        New_server_pointing.resize(600, 320)
        New_server_pointing.setMinimumSize(QtCore.QSize(600, 320))
        New_server_pointing.setMaximumSize(QtCore.QSize(600, 320))
        New_server_pointing.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(New_server_pointing)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 601, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 10, 84, 171))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(210, 10, 284, 171))
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(260, 32))
        self.comboBox.setMaximumSize(QtCore.QSize(260, 32))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(260, 32))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(260, 32))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 250, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 250, 76, 32))
        self.pushButton.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 133, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        New_server_pointing.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(New_server_pointing)
        self.statusbar.setObjectName("statusbar")
        New_server_pointing.setStatusBar(self.statusbar)

        self.retranslateUi(New_server_pointing)
        QtCore.QMetaObject.connectSlotsByName(New_server_pointing)

    def retranslateUi(self, New_server_pointing):
        _translate = QtCore.QCoreApplication.translate
        New_server_pointing.setWindowTitle(_translate("New_server_pointing", "新增服务器指向"))
        self.label_2.setText(_translate("New_server_pointing", "协议类型"))
        self.label.setText(_translate("New_server_pointing", "连接名称"))
        self.label_3.setText(_translate("New_server_pointing", "服务器IP"))
        self.label_4.setText(_translate("New_server_pointing", "端口"))
        self.comboBox.setItemText(0, _translate("New_server_pointing", "sziot"))
        self.comboBox.setItemText(1, _translate("New_server_pointing", "Touchuan"))
        self.comboBox.setItemText(2, _translate("New_server_pointing", "MQTT"))
        self.pushButton_2.setText(_translate("New_server_pointing", "取消"))
        self.pushButton.setText(_translate("New_server_pointing", "确定"))
import shuncom_qrc_rc
