# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 812)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico2/检测.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QGroupBox#groupBox_2\n"
"{\n"
"    border : none;\n"
"}\n"
"\n"
"\n"
"/*checkbox样式设置*/\n"
"QCheckBox::indicator { \n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"/*未选中*/\n"
"QCheckBox::indicator::unchecked {   \n"
"    border-image: url(:/png/shuncom_ico/png_ico2/复选框.png);\n"
"}\n"
"/*选中*/\n"
"QCheckBox::indicator::checked { \n"
"   border-image:url(:/png/shuncom_ico/png_ico2/复选框-选中.png);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;\n"
"    height:500px    \n"
"}\n"
"\n"
"\n"
"\n"
"QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(107, 107, 107);\n"
"        background: white;\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(80, 80, 80);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*鼠标右键菜单样式*/\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"/*滚动条样式*/\n"
"\n"
"/*QScrollBar Style*/\n"
"\n"
"/*纵向滚动条*/\n"
"QScrollBar:vertical {\n"
"    width: 10px; /*宽度*/\n"
"    background: transparent;\n"
"    margin: 0px 0px 0px 0px; /**/\n"
"}\n"
"/*横向滚动条*/\n"
"QScrollBar:horizontal {\n"
"    /*background: transparent;*/\n"
"    height: 10px; /*高度*/\n"
"    background: transparent;\n"
"    margin: 0px 0px 0px 0px;\n"
"    \n"
"}\n"
"\n"
"/*当鼠标放到纵向或者横向滚动条上面时*/\n"
"QScrollBar:vertical:hover,QScrollBar:horizontal:hover {\n"
"    background: rgba(0, 0, 0, 30); /*修改背景透明度 30*/\n"
"    border-radius: 5px; /*圆角*/\n"
"}\n"
"\n"
"/*纵向滚动条上面的滑块*/\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(0, 0, 0, 50);\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"/*横向滚动条上面的滑块*/\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(0, 0, 0, 50);\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"    border: none;\n"
"}\n"
"\n"
"/*当鼠标放到滚动条滑块上面时改变透明度实现颜色的深浅变化*/\n"
"QScrollBar::handle:vertical:hover,QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"/*纵向滚动条下部分块*/\n"
"QScrollBar::add-page:vertical {\n"
"    width: 10px;\n"
"    color : argb(100, 0, 0, 0);\n"
"    background-color: argb(50, 0, 0, 0);   /* 空白区域的背景色*/\n"
"}\n"
"/*横向滚动条后面部分块*/\n"
"QScrollBar::add-page:horizontal {\n"
"    height: 10px;\n"
"    color : argb(100, 0, 0, 0);\n"
"    background-color: argb(50, 0, 0, 0);   /* 空白区域的背景色*/\n"
"}\n"
"/*纵向滚动条上面部分块*/\n"
"QScrollBar::sub-page:vertical {\n"
"    width: 10px;\n"
"    color : argb(100, 0, 0, 0);\n"
"    background-color: argb(50, 0, 0, 0);   /* 空白区域的背景色*/\n"
"}\n"
"/*横向滚动条左部分块*/\n"
"QScrollBar::sub-page:horizontal {\n"
"    height: 10px;\n"
"    color : argb(100, 0, 0, 0);\n"
"    background-color: argb(50, 0, 0, 0);   /* 空白区域的背景色*/\n"
"}\n"
"/*纵向滚动条顶部三角形位置*/\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 12px;\n"
"    width: 10px;\n"
"    background: transparent;\n"
"    subcontrol-position: top;\n"
"}\n"
"/*横向滚动条左侧三角形位置*/\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 10px;\n"
"    width: 12px;\n"
"    background: transparent;\n"
"    subcontrol-position: left;\n"
"}\n"
"\n"
"/*纵向滚动条下面三角形部分*/\n"
"QScrollBar::add-line:vertical {\n"
"    height: 12px;\n"
"    width: 10px;\n"
"    background: transparent;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"/*横向滚动条右边的三角形部分*/\n"
"QScrollBar::add-line:horizontal {\n"
"    height: 10px;\n"
"    width: 12px;\n"
"    background: transparent;\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"/*表格样式*/\n"
"/*设置表头样式*/\n"
"/**/\n"
"QHeaderView::section {\n"
"    background-color:#F7F8FA;     /*背景色 白色*/\n"
"    border:0px solid #E0DDDC;   /*先把边框宽度设为0，即隐藏所有表头边框*/\n"
"    height:56px;                /*表头高度*/\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setStyleSheet("background-color: rgb(21, 133, 212);\n"
"\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setMinimumSize(QtCore.QSize(112, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体设置*/\n"
"    font: 75 10pt \"苹方 粗体\";\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color::rgb(0,85,255);\n"
"    /*无边框*/\n"
"    border : none;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/设置1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(25, 30))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_17.addWidget(self.pushButton, 2, 5, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_17.addWidget(self.label_2, 1, 0, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_17.addWidget(self.line_2, 0, 0, 1, 7)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber.setMinimumSize(QtCore.QSize(100, 30))
        self.lcdNumber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcdNumber.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lcdNumber.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lcdNumber.setStyleSheet("color: rgb(255, 255, 255);\n"
"border :none;\n"
"font: 75 11pt \"微软雅黑\";")
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_17.addWidget(self.lcdNumber, 3, 0, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_17.setMinimumSize(QtCore.QSize(160, 30))
        self.groupBox_17.setMaximumSize(QtCore.QSize(160, 30))
        self.groupBox_17.setStyleSheet("border : none;\n"
"background: rgba(0, 0, 0, 50);")
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_17)
        self.comboBox.setMinimumSize(QtCore.QSize(160, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.comboBox.setStyleSheet("/*普通的样式*/\n"
"QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(21, 133, 212);\n"
"    border : none;\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体样式 */\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid grey;   /* 选定项的虚框 */\n"
"    border: 0px solid grey;   /* 整个下拉窗体的边框 */\n"
"    color: rgb(50, 50, 51);\n"
"    height: 160px;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-color: rgb(0, 0, 0); \n"
"    selection-background-color: rgb(247, 248, 250);   /* 整个下拉窗体被选中项的背景色 */\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 32px;   /* 项的高度（设置pComboBox->setView(new QListView());后，该项才起作用） */\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:checked {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    color: rgb(21, 117, 212);\n"
"    background-color: rgb(247, 248, 250);\n"
"}\n"
"\n"
"/* 下拉框样式 */\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}\n"
"\n"
"/* 下拉箭头样式 */\n"
"QComboBox::down-arrow{\n"
"    image : url(:/png/shuncom_ico/png_ico/下拉2.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"/* 点击下拉箭头 */\n"
" QComboBox::down-arrow:on { \n"
"　　 /* 显示上拉箭头 */\n"
"    image: url(:/png/shuncom_ico/png_ico/上箭头-白.png);\n"
" }\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setIconSize(QtCore.QSize(20, 20))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_17, 3, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(568, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem, 1, 4, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(154, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体设置*/\n"
"    font: 75 10pt \"苹方 粗体\";\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(21, 133, 212);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    /*无边框*/\n"
"    border : none;\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/刷新2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_17.addWidget(self.pushButton_2, 2, 6, 2, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_17.addWidget(self.line, 1, 1, 3, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_17.addWidget(self.label_3, 1, 2, 2, 2)
        self.gridLayout_6.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border : none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setMinimumSize(QtCore.QSize(86, 32))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/  \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color::rgb(0,85,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/设置3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoRepeat(False)
        self.pushButton_3.setAutoExclusive(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(72, 32))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color::rgb(0,85,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/删除1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setMinimumSize(QtCore.QSize(72, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(72, 16777215))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color::rgb(0,85,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/上传3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setMinimumSize(QtCore.QSize(20, 25))
        self.pushButton_10.setMaximumSize(QtCore.QSize(20, 25))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色为白色*/    \n"
"    color: rgb(0, 0, 0);\n"
"     /*背景颜色*/  \n"
"    background-color::rgb(0,85,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:8px;\n"
"    width:40px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*图标*/  \n"
"    icon : url(:/png/shuncom_ico/png_ico/搜索-蓝.png);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*图标*/  \n"
"    icon : url(:/png/shuncom_ico/png_ico/搜索-湛蓝.png);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_10.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/搜索1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 25))
        self.lineEdit.setStyleSheet("/*鼠标右键菜单样式*/\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QLineEdit{border : none};")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(100)
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setStyleSheet("")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_3.setMaximumSize(QtCore.QSize(137, 16777215))
        self.tableWidget_3.setStyleSheet("/*表格前景样式*/\n"
"QTableWidget{\n"
"    border : none; /*设置成无边框*/\n"
"    background-color:#F7F8FA;     /*整个表格的背景色，这里为白色*/\n"
"    gridline-color:white;   /*这个是表格的格子线的颜色，为亮灰*/\n"
"}\n"
"\n"
"/*单元格被选中样式*/\n"
"/*QTableWidget::item:selected{\n"
"    color:#DCDCDC;\n"
"    background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #484848,stop:1 #383838);\n"
"}*/\n"
"\n"
"/*掠过单元格时的样式*/\n"
"QTableWidget::item:hover{\n"
"    color:rgb(21, 133, 212);/*设置字体颜色*/\n"
"}\n"
"")
        self.tableWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_3.setShowGrid(True)
        self.tableWidget_3.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico2/复选框-选中.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 51))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_3.setItem(13, 0, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(133)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(40)
        self.gridLayout_7.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setMinimumSize(QtCore.QSize(740, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        item = QtWidgets.QTableWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico2/复选框.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.gridLayout_7.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 560))
        self.groupBox_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_6.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"    background:rgba(255,255,255,255); /* 背景透明*/\n"
"\n"
"}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(15, 60))
        self.pushButton_11.setMaximumSize(QtCore.QSize(15, 60))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/左箭头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon9)
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setMinimumSize(QtCore.QSize(270, 612))
        self.groupBox_7.setMaximumSize(QtCore.QSize(270, 16777215))
        self.groupBox_7.setStyleSheet("QGroupBox#groupBox_7\n"
"{\n"
"    background-color : rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setStyleSheet("/*字体颜色*/    \n"
"    color: rgb(50, 50, 51);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_8.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yahei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_6.setStyleSheet("\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/修改.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon10)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_8.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setMinimumSize(QtCore.QSize(32, 32))
        self.label_5.setMaximumSize(QtCore.QSize(32, 32))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_8, 1, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_9.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_7.setIcon(icon10)
        self.pushButton_7.setFlat(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_9.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setMinimumSize(QtCore.QSize(32, 32))
        self.label_6.setMaximumSize(QtCore.QSize(32, 32))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_9, 2, 0, 1, 2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_10.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_8.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_8.setIcon(icon10)
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_10.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_10)
        self.label_7.setMinimumSize(QtCore.QSize(32, 32))
        self.label_7.setMaximumSize(QtCore.QSize(32, 32))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_10.addWidget(self.label_7, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_10, 3, 0, 1, 2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_11.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_11.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_12.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_12.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_12.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/升级-灰.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon11)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_11.addWidget(self.pushButton_12, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_11)
        self.label_8.setMinimumSize(QtCore.QSize(32, 32))
        self.label_8.setMaximumSize(QtCore.QSize(32, 32))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_11, 4, 0, 1, 2)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_12.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_12.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_13.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_13.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_13.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/校时-灰.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_12.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setMinimumSize(QtCore.QSize(32, 32))
        self.label_9.setMaximumSize(QtCore.QSize(32, 32))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_12, 5, 0, 1, 2)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_13.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_13.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_14.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_14.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_14.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"   background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/导出1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon13)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_13.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_13)
        self.label_10.setMinimumSize(QtCore.QSize(32, 32))
        self.label_10.setMaximumSize(QtCore.QSize(32, 32))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_13, 6, 0, 1, 2)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_14.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_14.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_15.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_15.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_15.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/重启1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon14)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_14.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_14)
        self.label_11.setMinimumSize(QtCore.QSize(32, 32))
        self.label_11.setMaximumSize(QtCore.QSize(32, 32))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_14, 7, 0, 1, 2)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_15.setMinimumSize(QtCore.QSize(235, 35))
        self.groupBox_15.setMaximumSize(QtCore.QSize(235, 35))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox_15)
        self.label_12.setMinimumSize(QtCore.QSize(32, 32))
        self.label_12.setMaximumSize(QtCore.QSize(32, 32))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_15.addWidget(self.label_12, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 32))
        self.pushButton_9.setMaximumSize(QtCore.QSize(200, 32))
        self.pushButton_9.setStyleSheet("/*QPushButton{border:none;background-color:white;}\n"
"    QPushButton{\n"
"        border:1px color: rgb(170, 170, 127);\n"
"        border-bottom:1px solid white;\n"
"        font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"    }\n"
"*/\n"
"\n"
"/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/定时重启-橙.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon15)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_15.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_15, 8, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem2, 9, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_16.setMinimumSize(QtCore.QSize(232, 50))
        self.groupBox_16.setMaximumSize(QtCore.QSize(232, 50))
        self.groupBox_16.setStyleSheet("QGroupBox#groupBox_16\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.line_4 = QtWidgets.QFrame(self.groupBox_16)
        self.line_4.setEnabled(True)
        self.line_4.setGeometry(QtCore.QRect(160, 30, 61, 20))
        self.line_4.setStyleSheet("color: rgb(50, 50, 51);\n"
"border-color: rgb(50, 50, 51);\n"
"gridline-color: rgb(50, 50, 51);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.groupBox_16)
        self.line_3.setWindowModality(QtCore.Qt.NonModal)
        self.line_3.setGeometry(QtCore.QRect(10, 30, 61, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.line_3.setFont(font)
        self.line_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_16)
        self.label_13.setGeometry(QtCore.QRect(80, 30, 71, 21))
        self.label_13.setStyleSheet("/*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_16.addWidget(self.groupBox_16, 10, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(220, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(220, 32))
        self.lineEdit_2.setStyleSheet("border : none;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_16.addWidget(self.lineEdit_2, 11, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem3, 12, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_17.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_17.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:7pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(21, 117, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 0, 0);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_16.addWidget(self.pushButton_17, 12, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_16.setMinimumSize(QtCore.QSize(220, 32))
        self.pushButton_16.setMaximumSize(QtCore.QSize(220, 32))
        self.pushButton_16.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 133, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_16.addWidget(self.pushButton_16, 13, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_6, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网关局域网调试工具"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#323233;\">设置网段</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "设置网段"))
        self.label_2.setText(_translate("MainWindow", "在线设备数量"))
        self.comboBox.setItemText(0, _translate("MainWindow", "全部"))
        self.comboBox.setItemText(1, _translate("MainWindow", "星盒"))
        self.comboBox.setItemText(2, _translate("MainWindow", "聚盒四代"))
        self.comboBox.setItemText(3, _translate("MainWindow", "云盒二代"))
        self.comboBox.setItemText(4, _translate("MainWindow", "云盒四代"))
        self.pushButton_2.setText(_translate("MainWindow", "刷新网段设备"))
        self.label_3.setText(_translate("MainWindow", "产品类型"))
        self.pushButton_3.setText(_translate("MainWindow", "列设置"))
        self.pushButton_5.setText(_translate("MainWindow", "删除"))
        self.pushButton_4.setText(_translate("MainWindow", "导出"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "搜索MAC地址、设备IP"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "列名"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidget_3.item(1, 0)
        item.setText(_translate("MainWindow", "设备类别"))
        item = self.tableWidget_3.item(2, 0)
        item.setText(_translate("MainWindow", "MAC地址"))
        item = self.tableWidget_3.item(3, 0)
        item.setText(_translate("MainWindow", "固件版本号"))
        item = self.tableWidget_3.item(4, 0)
        item.setText(_translate("MainWindow", "硬件型号"))
        item = self.tableWidget_3.item(5, 0)
        item.setText(_translate("MainWindow", "连接方式"))
        item = self.tableWidget_3.item(6, 0)
        item.setText(_translate("MainWindow", "设备IP地址"))
        item = self.tableWidget_3.item(7, 0)
        item.setText(_translate("MainWindow", "HTTP端口"))
        item = self.tableWidget_3.item(8, 0)
        item.setText(_translate("MainWindow", "子网掩码"))
        item = self.tableWidget_3.item(9, 0)
        item.setText(_translate("MainWindow", "SZIOT服务器IP地址:端口"))
        item = self.tableWidget_3.item(10, 0)
        item.setText(_translate("MainWindow", "SZTT服务器IP地址:端口"))
        item = self.tableWidget_3.item(11, 0)
        item.setText(_translate("MainWindow", "MQTT服务器IP地址:端口"))
        item = self.tableWidget_3.item(12, 0)
        item.setText(_translate("MainWindow", "Zigbee频点"))
        item = self.tableWidget_3.item(13, 0)
        item.setText(_translate("MainWindow", "Zigbee频点ID"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "设备类别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MAC地址"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "固件版本号"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "硬件型号"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "连接方式"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "设备IP地址"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "HTTP端口"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "子网掩码"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "SZIOT服务器IP地址:端口"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "SZTT服务器IP地址:端口"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "MQTT服务器IP地址:端口"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Zigbee频点"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Zigbee频点ID"))
        self.label_4.setText(_translate("MainWindow", "操作"))
        self.pushButton_6.setText(_translate("MainWindow", " 修改设备IP "))
        self.pushButton_7.setText(_translate("MainWindow", " 修改服务器指向 "))
        self.pushButton_8.setText(_translate("MainWindow", " 修改Zigbee主站 "))
        self.pushButton_12.setText(_translate("MainWindow", "固件升级"))
        self.pushButton_13.setText(_translate("MainWindow", "校时"))
        self.pushButton_14.setText(_translate("MainWindow", "恢复出厂设置"))
        self.pushButton_15.setText(_translate("MainWindow", "立即重启"))
        self.pushButton_9.setText(_translate("MainWindow", "定时重启"))
        self.label_13.setText(_translate("MainWindow", "密码校验"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.pushButton_17.setText(_translate("MainWindow", "管理员登录"))
        self.pushButton_16.setText(_translate("MainWindow", "应用"))
import shuncom_qrc_rc
