# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_version_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_version_information(object):
    def setupUi(self, tool_version_information):
        tool_version_information.setObjectName("tool_version_information")
        tool_version_information.resize(310, 225)
        tool_version_information.setMinimumSize(QtCore.QSize(310, 225))
        tool_version_information.setMaximumSize(QtCore.QSize(310, 225))
        tool_version_information.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color : rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(tool_version_information)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 10, 311, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(98, 50, 191, 131))
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(71, 0))
        self.label_5.setMaximumSize(QtCore.QSize(71, 16777215))
        self.label_5.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    \n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(0, 0, 0);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/帮助.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 91, 131))
        self.groupBox_2.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        tool_version_information.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_version_information)
        self.statusbar.setObjectName("statusbar")
        tool_version_information.setStatusBar(self.statusbar)

        self.retranslateUi(tool_version_information)
        QtCore.QMetaObject.connectSlotsByName(tool_version_information)

    def retranslateUi(self, tool_version_information):
        _translate = QtCore.QCoreApplication.translate
        tool_version_information.setWindowTitle(_translate("tool_version_information", "版本信息"))
        self.label_4.setText(_translate("tool_version_information", "顺舟网关局域网调试工具"))
        self.label_5.setText(_translate("tool_version_information", "V1.0.1"))
        self.pushButton.setText(_translate("tool_version_information", "操作手册"))
        self.label.setText(_translate("tool_version_information", "软件名称"))
        self.label_2.setText(_translate("tool_version_information", "版本号"))
        self.label_3.setText(_translate("tool_version_information", "用户手册"))
import shuncom_qrc_rc
