# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_search_set.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_search_set(object):
    def setupUi(self, tool_search_set):
        tool_search_set.setObjectName("tool_search_set")
        tool_search_set.resize(600, 300)
        tool_search_set.setMinimumSize(QtCore.QSize(600, 300))
        tool_search_set.setMaximumSize(QtCore.QSize(600, 300))
        tool_search_set.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color : rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(tool_search_set)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 601, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(200, 30, 291, 151))
        self.groupBox_3.setStyleSheet("QGroupBox\n"
"{\n"
"    border : none;\n"
"\n"
"}\n"
"QSpinBox\n"
"{\n"
"    border : none;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 40))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 40))
        self.groupBox_2.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setStyleSheet("color: rgb(50, 50, 51);")
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(290, 55))
        self.groupBox_4.setMaximumSize(QtCore.QSize(290, 55))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_4.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_4.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_3.addWidget(self.spinBox_4, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_3.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_3.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 3, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_2.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_2.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 5, 1, 1)
        self.spinBox_1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_1.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_1.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_1.setMinimum(1)
        self.spinBox_1.setMaximum(255)
        self.spinBox_1.setObjectName("spinBox_1")
        self.gridLayout_3.addWidget(self.spinBox_1, 0, 6, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(290, 55))
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 55))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_8.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_8.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setMaximum(255)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_5.addWidget(self.spinBox_8, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_7.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_7.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setMaximum(255)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_5.addWidget(self.spinBox_7, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 3, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_6.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_6.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_5.addWidget(self.spinBox_6, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 5, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_5.setMinimumSize(QtCore.QSize(50, 32))
        self.spinBox_5.setMaximumSize(QtCore.QSize(50, 32))
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setMaximum(254)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_5.addWidget(self.spinBox_5, 0, 6, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(110, 30, 81, 151))
        self.groupBox_5.setStyleSheet("border : none;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 240, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 240, 76, 32))
        self.pushButton.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    /**/\n"
"    background-color: rgb(21, 133, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        tool_search_set.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_search_set)
        self.statusbar.setObjectName("statusbar")
        tool_search_set.setStatusBar(self.statusbar)

        self.retranslateUi(tool_search_set)
        self.radioButton.clicked['bool'].connect(self.groupBox_4.setDisabled)
        self.radioButton.clicked['bool'].connect(self.groupBox_6.setDisabled)
        self.radioButton_2.clicked['bool'].connect(self.groupBox_4.setEnabled)
        self.radioButton_2.clicked['bool'].connect(self.groupBox_6.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(tool_search_set)

    def retranslateUi(self, tool_search_set):
        _translate = QtCore.QCoreApplication.translate
        tool_search_set.setWindowTitle(_translate("tool_search_set", "设置搜索网段"))
        self.radioButton.setText(_translate("tool_search_set", "当前网段"))
        self.radioButton_2.setText(_translate("tool_search_set", "其他网段"))
        self.label_2.setText(_translate("tool_search_set", "."))
        self.label_3.setText(_translate("tool_search_set", "."))
        self.label_4.setText(_translate("tool_search_set", "."))
        self.label_8.setText(_translate("tool_search_set", "."))
        self.label_7.setText(_translate("tool_search_set", "."))
        self.label_6.setText(_translate("tool_search_set", "."))
        self.label_24.setText(_translate("tool_search_set", "终止IP"))
        self.label.setText(_translate("tool_search_set", "模式"))
        self.label_5.setText(_translate("tool_search_set", "起始IP"))
        self.pushButton_2.setText(_translate("tool_search_set", "取消"))
        self.pushButton.setText(_translate("tool_search_set", "确定"))
import shuncom_qrc_rc
