# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_factory_reset.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_factory_reset(object):
    def setupUi(self, tool_factory_reset):
        tool_factory_reset.setObjectName("tool_factory_reset")
        tool_factory_reset.resize(600, 200)
        tool_factory_reset.setMinimumSize(QtCore.QSize(600, 200))
        tool_factory_reset.setMaximumSize(QtCore.QSize(600, 200))
        tool_factory_reset.setStyleSheet("QMainWindow\n"
"{\n"
"    background-color : rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    border : none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(tool_factory_reset)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 600, 91))
        self.groupBox.setMinimumSize(QtCore.QSize(600, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 30, 169, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    \n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(217, 54, 54);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/shuncom_ico/png_ico/恢复出厂设置-白.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 150, 157, 19))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 140, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(255, 255, 255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        tool_factory_reset.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_factory_reset)
        self.statusbar.setObjectName("statusbar")
        tool_factory_reset.setStatusBar(self.statusbar)

        self.retranslateUi(tool_factory_reset)
        QtCore.QMetaObject.connectSlotsByName(tool_factory_reset)

    def retranslateUi(self, tool_factory_reset):
        _translate = QtCore.QCoreApplication.translate
        tool_factory_reset.setWindowTitle(_translate("tool_factory_reset", "恢复出厂设置"))
        self.label.setText(_translate("tool_factory_reset", "恢复出厂"))
        self.pushButton.setText(_translate("tool_factory_reset", "恢复出厂"))
        self.label_2.setText(_translate("tool_factory_reset", "已选择设备数:"))
        self.pushButton_2.setText(_translate("tool_factory_reset", "取消"))
import shuncom_qrc_rc
