# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_reboot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tool_reboot(object):
    def setupUi(self, tool_reboot):
        tool_reboot.setObjectName("tool_reboot")
        tool_reboot.resize(600, 260)
        tool_reboot.setMinimumSize(QtCore.QSize(600, 260))
        tool_reboot.setMaximumSize(QtCore.QSize(600, 260))
        tool_reboot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(tool_reboot)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 601, 151))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 30, 84, 95))
        self.groupBox_2.setStyleSheet("border : none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setStyleSheet("color: rgb(50, 50, 51);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setStyleSheet("color: rgb(50, 50, 51);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 30, 288, 95))
        self.groupBox_3.setStyleSheet("border : none;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 32))
        self.groupBox_4.setMaximumSize(QtCore.QSize(160, 32))
        self.groupBox_4.setStyleSheet("QRadioButton::indicator:checked\n"
"{\n"
"    border-image:url(:/png/shuncom_ico/png_ico/单选框.png)\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(51, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(135, 32))
        self.comboBox.setMaximumSize(QtCore.QSize(135, 32))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border : none;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/png/shuncom_ico/png_ico/下拉4.png);\n"
"    hight : 16px;\n"
"    width : 16px;\n"
"    \n"
"}\n"
"QComboBox::drop-down{\n"
"    border-style: none;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 32))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.timeEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.timeEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeEdit.setStyleSheet("QTimeEdit\n"
"{\n"
"    \n"
"    color: rgb(50, 50, 51);\n"
"    border-radius:1px;\n"
"    \n"
"    \n"
"}\n"
"QTimeEdit::up-button\n"
"{\n"
"    image:none;\n"
"}\n"
"\n"
"\n"
"QTimeEdit::down-button\n"
"{\n"
"    \n"
"    image:none;\n"
"}\n"
"")
        self.timeEdit.setFrame(False)
        self.timeEdit.setKeyboardTracking(True)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_3.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setMinimumSize(QtCore.QSize(30, 30))
        self.label_3.setMaximumSize(QtCore.QSize(30, 30))
        self.label_3.setStyleSheet("image: url(:/png/shuncom_ico/png_ico/时钟.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 210, 157, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("color: rgb(98, 98, 102);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(50, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(510, 200, 76, 32))
        self.pushButton.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"\n"
"\n"
"    /*字体颜色*/ \n"
"    color: rgb(255, 255, 255);\n"
"     /*背景颜色*/  \n"
"    background-color: rgb(21, 91, 212);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:0px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 200, 76, 32))
        self.pushButton_2.setMinimumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(76, 32))
        self.pushButton_2.setStyleSheet("/*按钮普通态*/\n"
"QPushButton\n"
"{\n"
"    /*字体为微软雅黑*/\n"
"    font-family:Microsoft Yahei;\n"
"    /*字体大小为20点*/\n"
"    font-size:10pt;\n"
"    /*字体颜色*/ \n"
"    color: rgb(50, 50, 51);\n"
"     /*背景颜色*/  \n"
"    background-color:rgb(255,255,255);\n"
"    /*边框圆角半径为8像素*/ \n"
"    border-radius:2px;\n"
"    width:65px;\n"
"}\n"
" \n"
"/*按钮停留态*/\n"
"QPushButton:hover\n"
"{\n"
"   /*背景颜色*/  \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
" \n"
"/*按钮按下态*/\n"
"QPushButton:pressed\n"
"{\n"
"    /*背景颜色*/  \n"
"     background-color:rgb(170 , 255 , 255);\n"
"    /*左内边距为3像素，让按下时字向右移动3像素*/  \n"
"    padding-left:3px;\n"
"    /*上内边距为3像素，让按下时字向下移动3像素*/  \n"
"    padding-top:3px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        tool_reboot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tool_reboot)
        self.statusbar.setObjectName("statusbar")
        tool_reboot.setStatusBar(self.statusbar)

        self.retranslateUi(tool_reboot)
        QtCore.QMetaObject.connectSlotsByName(tool_reboot)

    def retranslateUi(self, tool_reboot):
        _translate = QtCore.QCoreApplication.translate
        tool_reboot.setWindowTitle(_translate("tool_reboot", "定时重启"))
        self.label.setText(_translate("tool_reboot", "自动重启"))
        self.label_2.setText(_translate("tool_reboot", "时间设置"))
        self.radioButton.setText(_translate("tool_reboot", "关闭"))
        self.radioButton_2.setText(_translate("tool_reboot", "开启"))
        self.comboBox.setItemText(0, _translate("tool_reboot", "每天"))
        self.comboBox.setItemText(1, _translate("tool_reboot", "星期一"))
        self.comboBox.setItemText(2, _translate("tool_reboot", "星期二"))
        self.comboBox.setItemText(3, _translate("tool_reboot", "星期三"))
        self.comboBox.setItemText(4, _translate("tool_reboot", "星期四"))
        self.comboBox.setItemText(5, _translate("tool_reboot", "星期五"))
        self.comboBox.setItemText(6, _translate("tool_reboot", "星期六"))
        self.comboBox.setItemText(7, _translate("tool_reboot", "星期天"))
        self.timeEdit.setDisplayFormat(_translate("tool_reboot", "HH:mm:ss"))
        self.label_8.setText(_translate("tool_reboot", "已选择设备数:"))
        self.pushButton.setText(_translate("tool_reboot", "确定"))
        self.pushButton_2.setText(_translate("tool_reboot", "取消"))
import shuncom_qrc_rc
